name: code

on:
  workflow_dispatch: 

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: code
        run: |
          git clone -b fongmi https://github.com/FongMi/TV code
          cd code
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git revert 8b41f5c
          git revert db47847
          cd ..

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b dev-1
          rm -rf .github
          cp -r code/* .
          cp -r code/.github .
          rm -rf code
          git add .
          git commit -m "commit"
          git push --force origin dev-1
