name: code

on:
  workflow_dispatch: 

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: code
        run: |
          git clone -b fongmi https://github.com/FongMi/TV TV
          cd TV
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git revert db47847
