name: code

on:
  workflow_dispatch: 

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: code
        run: |
          git clone -b release https://github.com/FongMi/TV code
          cd code
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          sed -i 's/return getUrl() != null \&\& getUrl().length() > 0;/\/\/return getUrl() != null \&\& getUrl().length() > 0;\n        return true;/' app/src/main/java/com/fongmi/android/tv/api/config/LiveConfig.java
          sed -i 's#parseConfig(Decoder.getJson(config.getUrl()), callback);#String url = config.getUrl();\n            //if (TextUtils.isEmpty(url)) {\n                url = "https://tv.lan2wan.top/candymuj1.json";\n              // 添加以下代码，解决内置源时，投屏播放问题，给定一个配置，写入本地数据库，标记一个name（名字“源已内置”可以随便取，但一定要有，type为1,表示直播）\n                Config.find(url, 1).name("⚠️看或更新直播点这喔").update();\n            //}\n            parseConfig(Decoder.getJson(config.getUrl()), callback);#' app/src/main/java/com/fongmi/android/tv/api/config/LiveConfig.java
          sed -i 's#checkJson(Json.parse(Decoder.getJson(config.getUrl())).getAsJsonObject(), callback);#String url = config.getUrl();\n            //if (TextUtils.isEmpty(url)) {\n                url = "https://tv.lan2wan.top/candymuj1.json";\n                // 添加以下代码，解决内置源时，投屏播放问题，给定一个配置，写入本地数据库，标记一个name（名字“源已内置”可以随便取，但一定要有，type为0,表示点播）\n                Config.find(url, 0).name("⚠️看或更新点播点这喔").update();\n            //}\n            checkJson(Json.parse(Decoder.getJson(config.getUrl())).getAsJsonObject(), callback);#' app/src/main/java/com/fongmi/android/tv/api/config/VodConfig.java
          sed -i 's#App.execute(() -> doInBackground(activity));#//App.execute(() -> doInBackground(activity));#' app/src/mobile/java/com/fongmi/android/tv/Updater.java
          sed -i 's#App.execute(() -> doInBackground(activity));#//App.execute(() -> doInBackground(activity));#' app/src/mobile/java/com/fongmi/android/tv/Updater.java
          sed -i 's#return Prefers.getBoolean("update", true);#//return Prefers.getBoolean("update", true);\n        return false;#' app/src/main/java/com/fongmi/android/tv/Setting.java
          cd ..

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b dev-7.0.1
          rm -rf .github
          cp -r code/* .
          cp -r code/.github .
          rm -rf code
          git add .
          git commit -m "commit"
          git push --force origin dev-7.0.1
